# Generated by Django 5.1.1 on 2024-09-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=100, unique=True)),
                ('totalAmount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('not-paid', 'Not-Paid')], default='Not-Paid', max_length=10)),
                ('utr', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
